[package]
name = "hubakc"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = { version = "2.6.0", features = ["https-native"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.9"
anyhow = "1.0.66"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true
